### ISSUE TITLE
Merging docs into the main repo

### ISSUE THREAD

**Issue by martijnbastiaan** [thoughtpolice/clash-docs#2]
Hey @thoughtpolice !

We're looking to [merge](https://github.com/clash-lang/clash-compiler/pull/962) this documentation into the main clash-compiler repository and work on it from there. Would you be okay with this? And would you be wiling to transfer ownership of clash-lang.readthedocs.io to us? (It doesn't seem natively supported by readthedocs.io, but maybe we could do something with delete+recreate.)

**Comment by thoughtpolice** [comment]
I thought there was a way to do this, I'll try to log in and see.

**Comment by thoughtpolice** [comment]
Yes, I can add maintainers to the project and I think that's all you'll need to get it working! If someone can create a readthedocs account, I'll add them, and archive this repository. Let's follow up in the original issue.
